services:
  - type: web
    name: portfolio-backend
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: PORT
        value: "5000"
